"""Teardrop SDK — Python client for the Teardrop AI agent API."""

from teardrop.client import AsyncTeardropClient, TeardropClient
from teardrop.exceptions import (
    APIError,
    AuthenticationError,
    ConflictError,
    ForbiddenError,
    GatewayError,
    NotFoundError,
    PaymentRequiredError,
    RateLimitError,
    TeardropError,
    ValidationError,
)
from teardrop.models import (
    MODELS_BY_PROVIDER,
    AddTrustedAgentRequest,
    AgentCard,
    AgentRunRequest,
    AgentTool,
    AgentToolsResponse,
    AgentWallet,
    AuthorConfig,
    BillingBalance,
    BillingHistoryEntry,
    BillingPricingResponse,
    CreateCustomToolRequest,
    # Backward-compat aliases
    CreateEventTriggerRequest,
    CreateMcpServerRequest,
    CreateOrgToolRequest,
    CreateScheduleRequest,
    CreditBalance,
    CreditHistoryEntry,
    CustomTool,
    DiscoverMcpToolsResponse,
    EarningsEntry,
    EventTrigger,
    EventTriggerWithSecret,
    Invoice,
    JwtPayloadBase,
    LinkWalletRequest,
    MarketplaceSubscription,
    MarketplaceTool,
    McpServerAuthType,
    McpToolDefinition,
    MemoryEntry,
    MeResponse,
    ModelBenchmarksResponse,
    ModelInfo,
    ModelPricing,
    ModelRunBenchmarks,
    OrgCredentialsEntry,
    OrgCredentialsResponse,
    OrgLlmConfig,
    OrgMcpServer,
    OrgTool,
    PricingInfo,
    ProviderType,
    RegenerateCredentialsResponse,
    RoutingPreference,
    ScheduledRun,
    ScheduledRunResult,
    ScheduledRunsPage,
    SetLlmConfigRequest,
    SSEEvent,
    StoreMemoryRequest,
    StripeTopupRequest,
    StripeTopupResponse,
    StripeTopupStatusResponse,
    TokenResponse,
    ToolPolicy,
    ToolPricing,
    TrustedAgent,
    UpdateEventTriggerRequest,
    UpdateMcpServerRequest,
    UpdateOrgToolRequest,
    UpdateScheduleRequest,
    UsageSummary,
    UsdcTopupRequest,
    UsdcTopupRequirements,
    Wallet,
    WithdrawRequest,
)
from teardrop.streaming import (
    EVENT_BILLING_SETTLEMENT,
    EVENT_CUSTOM,
    EVENT_DONE,
    EVENT_ERROR,
    EVENT_RUN_FINISHED,
    EVENT_RUN_STARTED,
    EVENT_SURFACE_UPDATE,
    EVENT_TEXT_MSG_CONTENT,
    EVENT_TEXT_MSG_END,
    EVENT_TEXT_MSG_START,
    EVENT_TOOL_CALL_END,
    EVENT_TOOL_CALL_START,
    EVENT_USAGE_SUMMARY,
    async_collect_text,
    collect_text,
    format_usdc,
    iter_sse_events,
    parse_marketplace_tool_name,
    parse_mcp_tool_name,
    parse_usdc,
)
from teardrop.webhook_verify import sign_webhook, verify_webhook

__all__ = [
    # Clients
    "AsyncTeardropClient",
    "TeardropClient",
    # Models - agent
    "AgentCard",
    "AgentRunRequest",
    "AgentTool",
    "AgentToolsResponse",
    "JwtPayloadBase",
    "MeResponse",
    "SSEEvent",
    "ToolPolicy",
    # Models - billing
    "BillingBalance",
    "BillingHistoryEntry",
    "BillingPricingResponse",
    "CreditBalance",
    "CreditHistoryEntry",
    "Invoice",
    "PricingInfo",
    "CreateScheduleRequest",
    "ScheduledRun",
    "ScheduledRunResult",
    "ScheduledRunsPage",
    "UpdateScheduleRequest",
    "CreateEventTriggerRequest",
    "EventTrigger",
    "EventTriggerWithSecret",
    "UpdateEventTriggerRequest",
    "StripeTopupRequest",
    "StripeTopupResponse",
    "StripeTopupStatusResponse",
    "TokenResponse",
    "ToolPricing",
    "UsdcTopupRequest",
    "UsdcTopupRequirements",
    "UsageSummary",
    # Models - wallets
    "LinkWalletRequest",
    "Wallet",
    # Models - org webhook tools
    "CreateOrgToolRequest",
    "OrgTool",
    "UpdateOrgToolRequest",
    # Models - MCP servers
    "McpServerAuthType",
    "OrgMcpServer",
    "CreateMcpServerRequest",
    "UpdateMcpServerRequest",
    "McpToolDefinition",
    "DiscoverMcpToolsResponse",
    # Models - memory
    "MemoryEntry",
    "StoreMemoryRequest",
    # Models - marketplace
    "AuthorConfig",
    "EarningsEntry",
    "MarketplaceSubscription",
    "MarketplaceTool",
    "WithdrawRequest",
    # Models - org credentials
    "OrgCredentialsEntry",
    "OrgCredentialsResponse",
    "RegenerateCredentialsResponse",
    # Models - A2A
    "AddTrustedAgentRequest",
    "TrustedAgent",
    # Models - agent wallets
    "AgentWallet",
    # Models - LLM config
    "OrgLlmConfig",
    "SetLlmConfigRequest",
    "ProviderType",
    "RoutingPreference",
    "MODELS_BY_PROVIDER",
    # Models - model benchmarks
    "ModelBenchmarksResponse",
    "ModelInfo",
    "ModelPricing",
    "ModelRunBenchmarks",
    # Backward-compat aliases
    "CreateCustomToolRequest",
    "CustomTool",
    # Exceptions
    "TeardropError",
    "AuthenticationError",
    "ForbiddenError",
    "PaymentRequiredError",
    "RateLimitError",
    "APIError",
    "NotFoundError",
    "ConflictError",
    "ValidationError",
    "GatewayError",
    # Streaming
    "async_collect_text",
    "collect_text",
    "format_usdc",
    "iter_sse_events",
    "parse_marketplace_tool_name",
    "parse_mcp_tool_name",
    "parse_usdc",
    "EVENT_BILLING_SETTLEMENT",
    "EVENT_CUSTOM",
    "EVENT_DONE",
    "EVENT_ERROR",
    "EVENT_RUN_FINISHED",
    "EVENT_RUN_STARTED",
    "EVENT_SURFACE_UPDATE",
    "EVENT_TEXT_MSG_CONTENT",
    "EVENT_TEXT_MSG_END",
    "EVENT_TEXT_MSG_START",
    "EVENT_TOOL_CALL_END",
    "EVENT_TOOL_CALL_START",
    "EVENT_USAGE_SUMMARY",
    "sign_webhook",
    "verify_webhook",
]
