"""Teardrop SDK — Python client for the Teardrop AI agent API."""

from teardrop.client import AsyncTeardropClient, TeardropClient
from teardrop.exceptions import (
    APIError,
    AuthenticationError,
    ConflictError,
    ForbiddenError,
    GatewayError,
    NotFoundError,
    PaymentRequiredError,
    RateLimitError,
    TeardropError,
    ValidationError,
)
from teardrop.models import (
    AgentCard,
    AgentRunRequest,
    BillingBalance,
    CreateCustomToolRequest,
    CreateMcpServerRequest,
    CreditHistoryEntry,
    CustomTool,
    DiscoverMcpToolsResponse,
    Invoice,
    McpServerAuthType,
    McpToolDefinition,
    OrgMcpServer,
    PricingInfo,
    SSEEvent,
    TokenResponse,
    UpdateMcpServerRequest,
    UsageSummary,
    Wallet,
)
from teardrop.streaming import (
    EVENT_BILLING_SETTLEMENT,
    EVENT_DONE,
    EVENT_ERROR,
    EVENT_RUN_FINISHED,
    EVENT_RUN_STARTED,
    EVENT_STATE_SNAPSHOT,
    EVENT_SURFACE_UPDATE,
    EVENT_TEXT_MSG_CONTENT,
    EVENT_TEXT_MSG_END,
    EVENT_TEXT_MSG_START,
    EVENT_TOOL_CALL_END,
    EVENT_TOOL_CALL_START,
    EVENT_USAGE_SUMMARY,
    async_collect_text,
    collect_text,
    iter_sse_events,
    parse_mcp_tool_name,
)

__all__ = [
    # Clients
    "AsyncTeardropClient",
    "TeardropClient",
    # Models - agent
    "AgentCard",
    "AgentRunRequest",
    "SSEEvent",
    # Models - billing
    "BillingBalance",
    "CreditHistoryEntry",
    "Invoice",
    "PricingInfo",
    "TokenResponse",
    "UsageSummary",
    "Wallet",
    # Models - org webhook tools
    "CreateCustomToolRequest",
    "CustomTool",
    # Models - MCP servers
    "McpServerAuthType",
    "OrgMcpServer",
    "CreateMcpServerRequest",
    "UpdateMcpServerRequest",
    "McpToolDefinition",
    "DiscoverMcpToolsResponse",
    # Exceptions
    "TeardropError",
    "AuthenticationError",
    "ForbiddenError",
    "PaymentRequiredError",
    "RateLimitError",
    "APIError",
    "NotFoundError",
    "ConflictError",
    "ValidationError",
    "GatewayError",
    # Streaming
    "async_collect_text",
    "collect_text",
    "iter_sse_events",
    "parse_mcp_tool_name",
    "EVENT_BILLING_SETTLEMENT",
    "EVENT_DONE",
    "EVENT_ERROR",
    "EVENT_RUN_FINISHED",
    "EVENT_RUN_STARTED",
    "EVENT_STATE_SNAPSHOT",
    "EVENT_SURFACE_UPDATE",
    "EVENT_TEXT_MSG_CONTENT",
    "EVENT_TEXT_MSG_END",
    "EVENT_TEXT_MSG_START",
    "EVENT_TOOL_CALL_END",
    "EVENT_TOOL_CALL_START",
    "EVENT_USAGE_SUMMARY",
]
