"""Teardrop SDK — Python client for the Teardrop AI agent API."""

from teardrop.client import AsyncTeardropClient, TeardropClient
from teardrop.exceptions import (
    APIError,
    AuthenticationError,
    ConflictError,
    ForbiddenError,
    GatewayError,
    NotFoundError,
    PaymentRequiredError,
    RateLimitError,
    TeardropError,
    ValidationError,
)
from teardrop.models import (
    AgentCard,
    AgentRunRequest,
    AuthorConfig,
    BillingBalance,
    BillingHistoryEntry,
    BillingPricingResponse,
    CreateMcpServerRequest,
    CreateOrgToolRequest,
    CreditBalance,
    CreditHistoryEntry,
    DiscoverMcpToolsResponse,
    EarningsEntry,
    Invoice,
    JwtPayloadBase,
    LinkWalletRequest,
    MODELS_BY_PROVIDER,
    MarketplaceTool,
    McpServerAuthType,
    McpToolDefinition,
    MemoryEntry,
    MemoryListResponse,
    ModelBenchmarksResponse,
    ModelInfo,
    ModelPricing,
    ModelRunBenchmarks,
    OrgLlmConfig,
    OrgMcpServer,
    OrgTool,
    PricingInfo,
    ProviderType,
    RoutingPreference,
    SSEEvent,
    SetLlmConfigRequest,
    StoreMemoryRequest,
    StripeTopupRequest,
    StripeTopupResponse,
    StripeTopupStatusResponse,
    TokenResponse,
    ToolPricing,
    UpdateMcpServerRequest,
    UpdateOrgToolRequest,
    UsdcTopupRequest,
    UsdcTopupRequirements,
    UsageSummary,
    Wallet,
    WithdrawRequest,
    # Backward-compat aliases
    CreateCustomToolRequest,
    CustomTool,
)
from teardrop.streaming import (
    EVENT_BILLING_SETTLEMENT,
    EVENT_DONE,
    EVENT_ERROR,
    EVENT_RUN_FINISHED,
    EVENT_RUN_STARTED,
    EVENT_SURFACE_UPDATE,
    EVENT_TEXT_MSG_CONTENT,
    EVENT_TOOL_CALL_END,
    EVENT_TOOL_CALL_START,
    EVENT_USAGE_SUMMARY,
    async_collect_text,
    collect_text,
    iter_sse_events,
    parse_mcp_tool_name,
)

__all__ = [
    # Clients
    "AsyncTeardropClient",
    "TeardropClient",
    # Models - agent
    "AgentCard",
    "AgentRunRequest",
    "JwtPayloadBase",
    "SSEEvent",
    # Models - billing
    "BillingBalance",
    "BillingHistoryEntry",
    "BillingPricingResponse",
    "CreditBalance",
    "CreditHistoryEntry",
    "Invoice",
    "PricingInfo",
    "StripeTopupRequest",
    "StripeTopupResponse",
    "StripeTopupStatusResponse",
    "TokenResponse",
    "ToolPricing",
    "UsdcTopupRequest",
    "UsdcTopupRequirements",
    "UsageSummary",
    # Models - wallets
    "LinkWalletRequest",
    "Wallet",
    # Models - org webhook tools
    "CreateOrgToolRequest",
    "OrgTool",
    "UpdateOrgToolRequest",
    # Models - MCP servers
    "McpServerAuthType",
    "OrgMcpServer",
    "CreateMcpServerRequest",
    "UpdateMcpServerRequest",
    "McpToolDefinition",
    "DiscoverMcpToolsResponse",
    # Models - memory
    "MemoryEntry",
    "MemoryListResponse",
    "StoreMemoryRequest",
    # Models - marketplace
    "AuthorConfig",
    "EarningsEntry",
    "MarketplaceTool",
    "WithdrawRequest",
    # Models - LLM config
    "OrgLlmConfig",
    "SetLlmConfigRequest",
    "ProviderType",
    "RoutingPreference",
    "MODELS_BY_PROVIDER",
    # Models - model benchmarks
    "ModelBenchmarksResponse",
    "ModelInfo",
    "ModelPricing",
    "ModelRunBenchmarks",
    # Backward-compat aliases
    "CreateCustomToolRequest",
    "CustomTool",
    # Exceptions
    "TeardropError",
    "AuthenticationError",
    "ForbiddenError",
    "PaymentRequiredError",
    "RateLimitError",
    "APIError",
    "NotFoundError",
    "ConflictError",
    "ValidationError",
    "GatewayError",
    # Streaming
    "async_collect_text",
    "collect_text",
    "iter_sse_events",
    "parse_mcp_tool_name",
    "EVENT_BILLING_SETTLEMENT",
    "EVENT_DONE",
    "EVENT_ERROR",
    "EVENT_RUN_FINISHED",
    "EVENT_RUN_STARTED",
    "EVENT_SURFACE_UPDATE",
    "EVENT_TEXT_MSG_CONTENT",
    "EVENT_TOOL_CALL_END",
    "EVENT_TOOL_CALL_START",
    "EVENT_USAGE_SUMMARY",
]

